on:
  pull_request:
    branches:
      - dev

name: PullRequest tests

jobs:
  pull_request_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build project
        uses: actions/setup-node@v2
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        with:
          args: install

      - uses: actions/cache@v2
        env:
          node-version: 14.1.0
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-node${{ env.node-version }}

      - name: Set development manifest
        run: |
          jq --argjson icons "{\"16\": \"icons/dev/16x16.png\",\"48\": \"icons/dev/48x48.png\",\"128\": \"icons/dev/128x128.png\"}" '.icons = $icons | .browser_action.default_icon = $icons | .name = "Liquality Wallet - Dev"' ./src/manifest.json > ./src/manifest.tmp
          mv ./src/manifest.tmp ./src/manifest.json

      - name: Build
        run: |
          npm ci
          npm run lint
          npm run build

      - run: mkdir screenshots
      - name: Run Smoke tests againt PullRequest
        uses: beemi/puppeteer-headful@v1.0.6
        env:
          CI: 'true'
          DISPLAY: :99
          SEED_WORDS: ${{ secrets.TEST_NET_SEED_WORDS }}
          TWENTY_FOUR_SEEDS: ${{ secrets.TWENTY_FOUR_SEEDS }}
        with:
          args: npm run pretest && npm run test:pullrequest:smoke

      - name: Run Dapp Injection Tests
        uses: beemi/puppeteer-headful@v1.0.6
        env:
          CI: 'true'
          DISPLAY: :99
          SEED_WORDS: ${{ secrets.TEST_NET_SEED_WORDS }}
          TWENTY_FOUR_SEEDS: ${{ secrets.TWENTY_FOUR_SEEDS }}
        with:
          args: npm run test:dappinjection

      - name: Allure report generation
        run: |
          sudo apt-add-repository ppa:qameta/allure
          sudo apt-get update
          sudo apt-get install allure
          npm run report

      - name: Allure report archive
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: allure-report
          path: allure-report

      - name: Save Screenshots
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: screenshots
          path: screenshots

