on:
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - 'release-candidate-*'
      - '!renovate/**'
      - '!dependabot/**'

name: PullRequest tests

jobs:
  pull_request_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Build project
        uses: actions/setup-node@v2.5.1
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        with:
          node-version: '14'
        # Create screenshots directory
      - run: mkdir screenshots

      - uses: actions/cache@v2.1.7
        id: cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-node${{ env.node-version }}

      # Create Dev Wallet with Dev agent for pull request tests.
      - name: Set development manifest (patch for DEV)
        env:
          VUE_APP_TERRA_MAINNET_URL: ${{ secrets.VUE_APP_TERRA_MAINNET_URL }}
          VUE_APP_AVALANCHE_MAINNET_NODE: ${{ secrets.VUE_APP_AVALANCHE_MAINNET_NODE }}
          VUE_APP_AVALANCHE_TESTNET_NODE: ${{ secrets.VUE_APP_AVALANCHE_TESTNET_NODE }}
          VUE_APP_NEAR_MAINNET_URL: ${{ secrets.VUE_APP_NEAR_MAINNET_URL }}
        run: |
          echo VUE_APP_TERRA_MAINNET_URL =${{ secrets.VUE_APP_TERRA_MAINNET_URL }} >> .env
          echo VUE_APP_AVALANCHE_MAINNET_NODE =${{ secrets.VUE_APP_AVALANCHE_MAINNET_NODE }} >> .env
          echo VUE_APP_AVALANCHE_TESTNET_NODE =${{ secrets.VUE_APP_AVALANCHE_TESTNET_NODE }} >> .env
          echo VUE_APP_NEAR_MAINNET_URL =${{ secrets.VUE_APP_NEAR_MAINNET_URL }} >> .env
          jq --argjson icons "{\"16\": \"icons/dev/16x16.png\",\"48\": \"icons/dev/48x48.png\",\"128\": \"icons/dev/128x128.png\"}" '.icons = $icons | .browser_action.default_icon = $icons | .name = "Liquality Wallet - Dev"' ./src/manifest.json > ./src/manifest.tmp
          mv ./src/manifest.tmp ./src/manifest.json
          npm ci
          npm run lint
          npm run build

      - name: Create wallet artifact
        uses: actions/upload-artifact@v2.3.1
        if: always()
        with:
          name: pull-request-wallet
          path: dist
          if-no-files-found: ignore
          retention-days: 30

      - name: Run Smoke tests againt PullRequest
        uses: beemi/puppeteer-headful@v1.0.11
        env:
          CI: 'true'
          DISPLAY: :99
          SEED_WORDS: ${{ secrets.TEST_NET_SEED_WORDS }}
          TWENTY_FOUR_SEEDS: ${{ secrets.TWENTY_FOUR_SEEDS }}
        with:
          args: npm run test:pullrequest

      - name: Save Screenshots
        uses: actions/upload-artifact@v2.3.1
        if: always()
        with:
          name: screenshots
          path: screenshots
          if-no-files-found: ignore

      - name: Discord notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_PULL_REQUESTS_WEBHOOK }}
          title: "${{ github.workflow}}"

